### ISSUE TITLE
Necessary to use client.auth.setSession() on login

### ISSUE THREAD

**Issue by YsarocK** [nuxt-modules/supabase#143]
Hello,

**ISSUE**
I've been using Nuxt RC14 & v0.3.0 of the module.
When using the `signInWithPassword()` method, I wanted to do a `navigateTo('/account')` on success.
On /account I had a middleware checking for `useSupabaseUser()` value, and if there was not, it redirected to /login.
Actually it didn't work because `useSupabaseUser()` was not updated unless page was reloaded.

**Workaround**
I figured it out by doing the following on successful authentification :
```
const client = useSupabaseClient()
client.auth.setSession(auth.session)
```
Where `auth` is the the result value .data of `signInWithPassword()`

In the middleware next, I don't use this anymore `useSupabaseUser()` but I use :
```
const client = useSupabaseClient()
const user = client.auth.getSession()
```

Now it works. 

I don't think It's normal but let me know if I miss something.

Thanks for all the team work.

**Comment by CareTiger** [comment]
I am having the same issue with useSupabaseUser(). Sometimes it works and the redirect works but sometimes it doesnt.

**Comment by jetlej** [comment]
Same here. Sometimes useSupabaseUser() is never updated even though I'm seeing the signIn event. Even when refreshing many times

**Comment by kyng-cytro** [comment]
I fixed the same issue by using the "watchEffect" method just like they did. It takes a while for the session to set and that causes the middleware check to miss.

**Comment by genu** [comment]
Another hacky workaround is to add a delay after a signin, like:

```ts
setTimeout(() => {
    router.push('/dashboard')
  }, 1000)

**Comment by CareTiger** [comment]
I have updated to the latest package ("@nuxtjs/supabase": "^0.3.5") and still have this issue.

**Comment by cccccccccccccccccnrd** [comment]
Having the same issue

**Comment by cccccccccccccccccnrd** [comment]
https://github.com/nuxt-modules/supabase/issues/144#issuecomment-1453513505 Just also mentioning this here as a possible solution.

**Comment by Zebnastien** [comment]
Same here: it looks there is a delay between Supabase signIn to success and useSupabaseUser to be set.

**Comment by larbish** [comment]
Should be fixed in latest version.
