### ISSUE TITLE
Can't deploy to Vercel Edge Functions to work if supabase module is present

### ISSUE THREAD

**Issue by Zebnastien** [nuxt-modules/supabase#158]
### Version
 "@nuxtjs/supabase": "^0.3.1",
    "nuxt": "^3.2.2"

### Steps to reproduce
- Start a new Nuxt 3 project.
- Install supabase module and add it to nuxt.config.ts modules array.
- In nuxt.config.ts, set nitro preset:
`nitro: {
    preset: "vercel-edge",
  },`
- Setup .env variables in Vercel.
- Deploy to Vercel.

### What is Expected?
When nitro preset is default node-js, everythings goes right.
With Vercel-edge preset, the same should happen.

### What is actually happening?
It builds but here is the result when you try to browse it:

![image](https://user-images.githubusercontent.com/64729974/219868170-946b3fb0-87e9-44dc-b7fe-b820d1c097d4.png)

And here is the log:

![image](https://user-images.githubusercontent.com/64729974/219868221-0b53b435-83dc-41e1-9b35-863068fca8d5.png)

**Comment by MarianMichalovic** [comment]
#120

**Comment by Zebnastien** [comment]
Thanks man !

**Comment by 9M6** [comment]
@Zebnastien Had same issue, I fixed it by simply adding this config to nuxt:

```
supabase: {
    client: {
      global: this,
    },
  },
```

But I don't think its a good solution, I think there needs to be a way to pass "globalThis" to that property so it works correctly.

**Comment by Pwntus** [comment]
This is still an issue for me. I can make it work if I switch to Vercel serverless function but it breaks on their edge functions.

**Comment by marc-tech** [comment]
I think this il link to a proxy probleme with /api that vercel use for edge function

**Comment by maximilian-schwarz** [comment]
"nuxt": "^3.4.1",
"@nuxtjs/supabase": "^0.3.5"

Deployed a project to Vercel with the edge present i got the following error:

```
TypeError: Cannot read properties of undefined (reading 'bind')
    at (index.mjs:1:493518)
    at (__nitro:middleware.js:1:17)
```

If i remove the @nuxtjs/supabase module everything is working fine.

**Comment by chasebank** [comment]
Sorry to add to the echoes, but I'm getting this same thing. Has anyone figured this out?

If anyone can take a crack at it, here's Vercel's default Nuxt starter for easier deploy: https://vercel.com/templates/nuxt/nuxtjs-boilerplate

So long as this module is included in the nuxt-config, deploy fails

**Comment by JuBertoo** [comment]
Hello, 
I still have the problem. Is there a solution?

**Comment by felipemarcos** [comment]
> "nuxt": "^3.4.1", "@nuxtjs/supabase": "^0.3.5"
> 
> Deployed a project to Vercel with the edge present i got the following error:
> 
> ```
> TypeError: Cannot read properties of undefined (reading 'bind')
>     at (index.mjs:1:493518)
>     at (__nitro:middleware.js:1:17)
> ```
> 
> If i remove the @nuxtjs/supabase module everything is working fine.

I fixed this error by patching the dependency `websocket` used by Supabase Realtime.

```diff
diff --git a/node_modules/websocket/lib/WebSocketConnection.js b/node_modules/websocket/lib/WebSocketConnection.js
index 219de63..ed68a65 100644
--- a/node_modules/websocket/lib/WebSocketConnection.js
+++ b/node_modules/websocket/lib/WebSocketConnection.js
@@ -32,9 +32,13 @@ const STATE_ENDING = 'ending';
 // Connection is fully closed.  No further data can be sent or received.
 const STATE_CLOSED = 'closed';
 
-var setImmediateImpl = ('setImmediate' in global) ?
-                            global.setImmediate.bind(global) :
-                            process.nextTick.bind(process);
+if ('setImmediate' in global) {
+    var setImmediateImpl = global.setImmediate.bind(global);
+} else if (typeof process !== 'undefined' && process.nextTick) {
+    var setImmediateImpl = process.nextTick.bind(process);
+} else {
+    var setImmediateImpl = function(fn) { setTimeout(fn, 0); };
+}
 
 var idCounter = 0;
```

Not sure if this code works because I don't use Realtime in my project, but it fixed the issue for me.

**Comment by alatalo** [comment]
Having the same issue. Thanks @felipemarcos your patch seems to help! (not using realtime myself either)
