### ISSUE TITLE
Uncaught SyntaxError: The requested module does not provide an export named 'default'

### ISSUE THREAD

**Issue by kaarelsirel** [nuxt-modules/supabase#172]
### Version
@nuxtjs/supabase: "^0.3.1"
nuxt: "^3.3.2"

### Reproduction Link

Fresh Nuxt 3 installation and @nuxtjs/supabase module with valid .env variables.

### Steps to reproduce

1. Create Nuxt 3 "^3.3.2" project.
2. Install @nuxtjs/supabase module.
3. Create .env file with valid `SUPABASE_URL` and `SUPABASE_KEY` variables.
4. Start development server `yarn dev -o`.

### What is Expected?
Supabase module to work properly.

### What is actually happening?
Error in console.
_The requested module '/_nuxt/node_modules/crypto-js/sha256.js?v=edd04760' does not provide an export named 'default' (at helpers.ts:2:8)_
![image](https://user-images.githubusercontent.com/18115386/229122930-b2f8bbc1-36fc-491f-bdb1-9b1d74dea004.png)

**Comment by mwohlan** [comment]
Workaround package.json for now:

```js
"resolutions": {
    "@supabase/gotrue-js": "2.16.0"
  }
```

**Comment by D4rkMindz** [comment]
This actually works for yarn.
For NPM, you could use
```json
  "overrides": {
    "@supabase/gotrue-js": "2.16.0"
  },
```

**Comment by cricadev** [comment]
just in case somebody is reading this thread and using pnpm.
`  "pnpm":{
    "overrides": {
      "@supabase/gotrue-js": "2.16.0"
    }
  }
  `
  thanks it's working from now, hopefully it will get fixed soon

**Comment by larbish** [comment]
Should be fixed in [v0.3.5](https://github.com/nuxt-modules/supabase/releases/tag/v0.3.5)

**Comment by ouhoy** [comment]
The issue is sadly still showing up on "@nuxtjs/supabase": "^1.3.5", "nuxt": "^3.10.3"
